# Generated by Django 5.0.6 on 2024-07-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajcas_app', '0002_configiration_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configiration',
            name='achievement',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='configiration',
            name='assisted_people',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='configiration',
            name='projects',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='configiration',
            name='years_experiences',
            field=models.IntegerField(max_length=6),
        ),
    ]
