# Generated by Django 5.0.6 on 2024-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajcas_app', '0012_remove_member_email_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_signed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
